#!/usr/bin/env python3
"""Create ignored placeholder profile files for a fresh checkout.

Existing files are never overwritten. The generated files are local working
copies that `/setup` can safely personalise without making them publishable.
"""

from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / ".framework" / "profile-templates"


def copy_if_missing(source: Path, destination: Path) -> bool:
    if destination.exists():
        return False
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)
    return True


def write_if_missing(destination: Path, content: str) -> bool:
    if destination.exists():
        return False
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    created: list[Path] = []
    profile_local = ROOT / ".framework" / "skills" / "job-application-assistant"

    for number, name in (
        ("01", "candidate-profile"),
        ("02", "behavioral-profile"),
        ("03", "writing-style"),
        ("04", "job-evaluation"),
        ("05", "cv-templates"),
        ("06", "cover-letter-templates"),
        ("07", "interview-prep"),
    ):
        filename = f"{number}-{name}.md"
        destination = profile_local / filename
        if copy_if_missing(TEMPLATES / filename, destination):
            created.append(destination)

    search_queries = ROOT / ".framework" / "skills" / "job-scraper" / "search-queries.md"
    if copy_if_missing(TEMPLATES / "search-queries.md", search_queries):
        created.append(search_queries)

    codex = ROOT / "CODEX.md"
    if write_if_missing(
        codex,
        "# Job Application Assistant\n\n"
        "<!-- Local profile generated by tools/bootstrap_private_profile.py. -->\n\n"
        "## Candidate Profile\n\n"
        "Run `/setup` to populate this private file.\n\n"
        "## Output convention\n\n"
        "Tailored CVs use `cv/main_<company>_<role>.tex`.\n",
    ):
        created.append(codex)

    brief = ROOT / ".codex" / "context" / "job-application-brief.md"
    if write_if_missing(
        brief,
        "# Job Application Brief\n\n"
        "Run `/setup` to populate this private local brief.\n\n"
        "Tailored CVs use `cv/main_<company>_<role>.tex`.\n",
    ):
        created.append(brief)

    evidence = ROOT / ".codex" / "context" / "evidence-bank.csv"
    if write_if_missing(
        evidence,
        "category,evidence,source,safe_wording,avoid_wording\n",
    ):
        created.append(evidence)

    master_cv = ROOT / "cv" / "master_cv.tex"
    if copy_if_missing(ROOT / "cv" / "main_example.tex", master_cv):
        created.append(master_cv)

    if created:
        print("Created local private profile placeholders:")
        for path in created:
            print(f"  - {path.relative_to(ROOT)}")
    else:
        print("Private profile files already exist; nothing changed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
